############################################################
##########         Control plane setup           ###########
############################################################

- hosts: k8s_controlplane
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
   - name: Create kubeadm config file
     template:
       src: ../templates/kubeadm-config.j2
       dest: /tmp/kubeadm-config.yaml
     delegate_to: "{{ hostvars[groups['k8s_controlplane'][0]]['ansible_default_ipv4']['address'] }}"

   - name: Intilizing Kubernetes Cluster
     command: kubeadm init --config=/tmp/kubeadm-config.yaml
     run_once: true
     delegate_to: "{{ hostvars[groups['k8s_controlplane'][0]]['ansible_default_ipv4']['address'] }}"

   - pause: seconds=30
   - name: Create directory for kube config.
     become_user: "{{ ansible_user }}"
     become_method: sudo
     become: yes
     file: 
       path: /home/{{ ansible_user }}/.kube
       state: directory
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: 0755
   - name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ ansible_user }}/.kube/config.
     become_user: root
     become_method: sudo
     become: yes
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/{{ ansible_user }}/.kube/config
       remote_src: yes
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: '0644'
   - pause: seconds=10
   - name: Remove the cache directory.
     become_user: "{{ ansible_user }}"
     become_method: sudo
     become: yes
     file: 
       path: /home/{{ ansible_user }}/.kube/cache
       state: absent
   - name: Create Pod Network.
     become_user: "{{ ansible_user }}"
     become_method: sudo
     become: yes
     shell: >
       curl -s https://docs.projectcalico.org/manifests/calico.yaml 
       | sed 's/# - name: CALICO_IPV4POOL_CIDR/- name: CALICO_IPV4POOL_CIDR/' 
       | sed 's/#   value: "192.168.0.0\/16"/  value: "{{ pod_network_cidr | replace("/","\/") }}"/' > /tmp/calico.yaml
       && kubectl apply -f /tmp/calico.yaml
     tags: calico
   - pause: seconds=30
   - name: Get the token for joining the nodes with Kuberentes master.
     # --ttl duration Default: 24h0m0s, let's tighen it up for security...
     shell: kubeadm token create  --print-join-command --ttl=5h
     register: kubernetes_join_command
     tags:
     - join-command
   - debug:
       msg: "{{ kubernetes_join_command.stdout }}"
   - name: Copy join command to local file.
     become: false
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

   - name: Configure kubectl command auto-completion.
     lineinfile:
       dest: /home/{{ ansible_user }}/.bashrc
       line: 'source <(kubectl completion bash)'
       insertafter: EOF

############################################################
##########            Worker setup               ###########
############################################################

- hosts: k8s_worker
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
   - name: Copy join command to worker nodes.
     become_user: "{{ ansible_user }}"
     become_method: sudo
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777   
   - name: Join the Worker nodes with the master.
     become: yes
     become_method: sudo
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not
   - debug:
       msg: "{{ joined_or_not.stdout }}"